
s1 = input().strip()          
s2 = input().strip()          
to_encrypt = input().strip()  
to_decrypt = input().strip()  
enc_table = str.maketrans(s1, s2)   
dec_table = str.maketrans(s2, s1)   
encrypted = to_encrypt.translate(enc_table)
decrypted = to_decrypt.translate(dec_table)
print(encrypted)
print(decrypted)
